apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mywebsite-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: liormilliger.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mywebsite-service
                port:
                  number: 80