apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mywebsite-servicemonitor
  namespace: default 
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: mywebsite 
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: web
      path: /metrics
      interval: 15s
      