replicas: 1
roles:
  master: "true"
  data: "true"
  ingest: "true"

persistence:
  enabled: true
  size: 20Gi
  storageClassName: gp3

# Required for a single-node cluster to start correctly
extraEnvs:
  - name: "discovery.type"
    value: "single-node"
  - name: "cluster.initial_master_nodes"
    value: "elasticsearch-master-0"