replicas: 1

roles:
  master: "true"
  data: "true"
  ingest: "true"

master:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: gp3

extraEnvs:
  - name: discovery.type
    value: single-node
