# clusterName: elasticsearch-single-node
# nodeGroup: master
replicas: 1

roles:
  # master: "true"
  data: "true"
  ingest: "true"

esConfig:
  elasticsearch.yml: |
    discovery.type: single-node

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
