daemonset:
  enabled: true
  
  extraEnvs:
    - name: ELASTIC_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-master-credentials
          key: password

  secretMounts:
    - name: elasticsearch-http-certs
      secretName: elasticsearch-master-certs # Secret created by the ES chart
      path: /usr/share/filebeat/certs/http

filebeatConfig:
  filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
      
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

      output.elasticsearch:
        hosts: ["https://elasticsearch-master.logging.svc:9200"]
        username: "elastic"
        password: "${ELASTIC_PASSWORD}"

        ssl:
          enabled: true
          ca_trusted_fingerprint: "" # Optional: for fingerprint verification
          certificate_authorities:
            - "/usr/share/filebeat/certs/http/ca.crt" # Path to the mounted CA
        
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"