daemonset:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: ${NODE_NAME}
            hints.enabled: true
            hints.default_config:
              type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
      
      processors:
        - add_kubernetes_metadata:
            in_cluster: true

      output.elasticsearch:
        hosts: ["elasticsearch-master.logging.svc:9200"]
        
  resources:
    requests:
      cpu: "100m"
      memory: "100Mi"
    limits:
      cpu: "200m"
      memory: "200Mi"