elasticsearchHosts: "https://elasticsearch-master.logging.svc:9200"

extraEnvs:
  - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
    valueFrom:
      secretKeyRef:
        name: kibana-es-token
        key: token

kibanaConfig:
  kibana.yml: |
    elasticsearch.serviceAccountToken: "${ELASTICSEARCH_SERVICEACCOUNTTOKEN}"
    elasticsearch.ssl.verificationMode: certificate
    elasticsearch.ssl.certificateAuthorities:
      - /usr/share/kibana/config/certs/ca.crt

secretMounts:
  - name: elasticsearch-master-certs
    secretName: elasticsearch-master-certs
    path: /usr/share/kibana/config/es-ca-certs

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"