apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana-token-creator-sa
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kibana-token-creator-role
  namespace: logging
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kibana-token-creator-binding
  namespace: logging
subjects:
- kind: ServiceAccount
  name: kibana-token-creator-sa
  namespace: logging
roleRef:
  kind: Role
  name: kibana-token-creator-role
  apiGroup: rbac.authorization.k8s.io