apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocd.proj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    path: argocd-apps
    targetRevision: HEAD
    helm:
      repo: 'git@github.com:liormilliger/mywebsite-k8s.git'
      chart: elasticsearch
      targetRevision: 8.5.1
      valueFiles:
        - ./values/es-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true