apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/liormilliger/mywebsite-k8s.git'
    targetRevision: main 
    path: 'argocd-apps' 
    helm:
      valueFiles:
        - helm-values/efk/elasticsearch-values.yaml
      chart: elasticsearch
      repoURL: https://helm.elastic.co
      targetRevision: 8.5.1 # Pinning chart version
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
