apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 1
        # No longer need 'discovery.type' or 'xpack' overrides.
        # We will use the chart's secure defaults.

        # This section tells the chart to generate self-signed certs for HTTP traffic.
        # It will create secrets to store these certificates.
        protocol: https
        http:
          tls:
            selfSignedCertificate:
              disabled: false
              # vvv ADD THESE LINES vvv
              subjectAltNames:
                - ip: 127.0.0.1
                - dns: localhost
                - dns: elasticsearch-master
                - dns: elasticsearch-master.logging
                - dns: elasticsearch-master.logging.svc
                - dns: elasticsearch-master.logging.svc.cluster.local

        # Storage configuration remains the same.
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"
          resources:
            requests:
              storage: 15Gi

        # Resource allocation remains the same.
        resources:
          requests:
            cpu: "100m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

