# Unified elastic-stack.yaml

# Application 1: Deploys the ECK Operator.
# The 'helm.values' block is added to prevent it from reinstalling cert-manager.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: eck-operator
    targetRevision: 2.11.1
    helm:
      values: |
        webhook:
          installCertManager: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# Application 2: Deploys the Elasticsearch and Kibana resources.
# This part remains unchanged.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoj.io
spec:
  project: default
  source:
    repoURL: https://github.com/liormilliger/mywebsite-k8s.git
    path: argocd-apps
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m