apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # vvv --- NEW REPO URL AND CHART --- vvv
    repoURL: https://charts.bitnami.com/bitnami
    chart: elasticsearch
    targetRevision: 19.16.2 # A recent, stable version
    helm:
      values: |
        global:
          storageClass: "gp2"
        # Configure a single-node cluster
        master:
          replicas: 1
          resources:
            requests:
              cpu: "100m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
        # Disable other node types for a minimal setup
        data:
          replicas: 0
        ingest:
          replicas: 0
        coordinating:
          replicas: 0
        # This is the magic part: Bitnami handles all the certificate
        # generation and SANs for you automatically.
        tls:
          autoGenerated: true
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      