apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argopd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        replicas: 1
        # Set discovery type for a single node to resolve the warning
        discovery:
          type: single-node
        # Explicitly disable the X-Pack security module to allow HTTP traffic
        xpack:
          security:
            enabled: false
        clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'
        resources:
          requests:
            cpu: "100m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "gp2"
          resources:
            requests:
              storage: 15Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
