# argocd-apps/fluentbit.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://fluent.github.io/helm-charts'
    chart: fluent-bit
    targetRevision: 0.45.0
    helm:
      releaseName: fluentbit
      valuesObject:
        # Create environment variables from the elasticsearch credentials secret
        extraEnv:
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                name: elasticsearch-master-credentials
                key: username
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-master-credentials
                key: password

        # Mount the elasticsearch CA certificate secret into the fluent-bit pods
        extraVolumes:
          - name: elastic-certs
            secret:
              secretName: elasticsearch-master-certs
        extraVolumeMounts:
          - name: elastic-certs
            mountPath: /fluent-bit/etc/certs/
            readOnly: true
        
        # Configure the Elasticsearch output plugin
        config:
          outputs: |
            [OUTPUT]
                Name            es
                Match           *
                Host            elasticsearch-master
                Port            9200
                # Add credentials for authentication
                Http_User       ${ELASTICSEARCH_USERNAME}
                Http_Passwd     ${ELASTICSEARCH_PASSWORD}
                # TLS settings for a secure connection
                TLS.VHost       elasticsearch-master  # <-- ADD THIS LINE
                TLS             On
                TLS.CA_File     /fluent-bit/etc/certs/ca.crt
                TLS.Verify      On
                Suppress_Type_Name On

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
