apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.45.0
    helm:
      values: |
        config:
          outputs: |
            [OUTPUT]
                Name            es
                Match           *
                Host            elasticsearch-master.logging.svc.cluster.local
                Port            9200
                Logstash_Format On
                Logstash_Prefix fluent-bit
                Replace_Dots    On
                Retry_Limit     False
                # Enable TLS for a secure connection
                TLS             On
                # Point to the CA certificate mounted from the secret created by Elasticsearch
                TLS.ca_file     /fluent-bit/certs/ca.crt
                # Provide credentials for authentication
                HTTP_User       elastic
                HTTP_Passwd     ${ELASTIC_PASSWORD}

        # Mount the secret containing the password for the 'elastic' user
        extraEnvVars:
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-cluster-credentials
                key: password

        # Mount the secret containing the self-signed CA certificate
        extraVolumes:
          - name: es-ca
            secret:
              secretName: elasticsearch-cluster-certs
        extraVolumeMounts:
          - name: es-ca
            mountPath: /fluent-bit/certs
            readOnly: true
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # Add a sync-wave to ensure this only deploys after Elasticsearch is ready and has created the secrets.
      # - SyncWave="1"

