apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/liormilliger/mywebsite-k8s.git'
    targetRevision: main 
    path: 'argocd-apps'
    helm:
      valueFiles:
        - helm-values/efk/fluentbit-values.yaml
      chart: fluent-bit
      repoURL: https://fluent.github.io/helm-charts
      targetRevision: 0.45.0 # Pinning chart version
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
