apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  annotations:
     argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argocroj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        # Connect to Elasticsearch over HTTPS
        elasticsearchHosts: "https://elasticsearch-master.logging.svc.cluster.local:9200"

        # Provide the CA certificate to Kibana so it can trust our Elasticsearch instance.
        # This references the secret automatically created by the Elasticsearch chart.
        elasticsearchCertificateAuthorities:
          - secretName: elasticsearch-master-certs

        # Credentials for Kibana to connect to Elasticsearch will be stored in a secret
        # that the pre-install job (which will now work) creates.
        elasticsearchRef:
          name: elasticsearch-master
          namespace: logging

        # Resource configuration remains the same.
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # # Add a sync-wave to ensure this only deploys after Elasticsearch is ready.
      # - SyncWave="1"

