apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocroj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: filebeat
    targetRevision: 8.5.1
    helm:
      values: |
        # Filebeat will be deployed as a DaemonSet, running one pod on each node of your cluster.
        daemonset:
          enabled: true
          # Mounts necessary host paths to collect logs from containers.
          filebeatConfig:
            filebeat.yml: |
              filebeat.autodiscover:
                providers:
                  - type: kubernetes
                    node: ${NODE_NAME}
                    hints.enabled: true
                    hints.default_config:
                      type: container
                      paths:
                        - /var/log/containers/*-${data.kubernetes.container.id}.log
              
              processors:
                - add_kubernetes_metadata:
                    in_cluster: true

              output.elasticsearch:
                hosts: ["elasticsearch-master.logging.svc:9200"]
                
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"

  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
