apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argocroj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        # This tells Kibana how to connect to the Elasticsearch service.
        # The service name 'elasticsearch-master' is the default created by the official Helm chart.
        elasticsearchHosts: ["http://elasticsearch-master.logging.svc:9200"]

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
