apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 8.5.1
    helm:
      values: |
        # This is the key fix:
        # Disable the pre-install hook that tries to create a token for a secure Elasticsearch.
        # This is necessary because we have security disabled on our Elasticsearch instance.
        managedServiceAccount: false

        # Continue to specify the HTTP connection details for Kibana itself.
        elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"

        # Resource configuration remains the same.
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

