apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 58.0.0 
    helm:
      # This is the key change
      # It tells Helm to skip applying CRDs during the normal sync
      skipCrds: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # This option prevents ArgoCD from adding the bloated annotation that causes the problem
      - ApplyOutOfSyncOnly=true
  
  # This section tells ArgoCD to sync the CRDs in a special, earlier phase
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration
