# A single-node cluster for development/portfolio purposes
replicas: 1
minimumMasterNodes: 1

# Configure persistent storage using the 'gp2' StorageClass
volumeClaimTemplate:
  storageClassName: gp2
  resources:
    requests:
      storage: 15Gi

esJavaOpts: "-Xms2g -Xmx2g"
resources:
  requests:
    cpu: "500m"
    memory: "4Gi"
  limits:
    cpu: "1"
    memory: "4Gi"
# --------------------------------------------------------------------