# This configures the output plugin to send logs to your Elasticsearch service
config:
  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master
        Port            9200
        Logstash_Format On
        Logstash_Prefix kube
        Replace_Dots    On
        Retry_Limit     False
        