# Point Kibana to the Elasticsearch service
elasticsearchHosts:
  - "http://elasticsearch-master:9200"

# Configure Ingress to access the Kibana UI
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kibana.liormilliger.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kibana-tls # cert-manager will create this secret
      hosts:
        - kibana.liormilliger.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    