# helm-values/efk/kibana-values.yaml

elasticsearchHosts:
  - "https://elasticsearch-master:9200" # <-- IMPORTANT: Change to https

# Add this entire section to mount the certificate secret from Elasticsearch
# and configure Kibana to use it.
extraVolumes:
  - name: elastic-certs
    secret:
      secretName: elasticsearch-master-certs

extraVolumeMounts:
  - name: elastic-certs
    mountPath: /usr/share/kibana/config/certs/
    readOnly: true

elasticsearch:
  ssl:
    certificateAuthorities: [ "/usr/share/kibana/config/certs/ca.crt" ]