# helm-values/efk/kibana-values.yaml

# By nesting the configuration like this, we bypass the chart's
# faulty template logic and write the value directly.
elasticsearch:
  hosts:
    - "http://elasticsearch-master:9200"

# Configure Ingress to access the Kibana UI
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kibana.liormilliger.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.liormilliger.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    