# helm-values/efk/kibana-values.yaml

# Correctly structured 'elasticsearch' block
elasticsearch:
  hosts:
    - "https://elasticsearch-master:9200"
  ssl:
    certificateAuthorities: [ "/usr/share/kibana/config/certs/ca.crt" ]

# Configure Ingress to access the Kibana UI
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: kibana.liormilliger.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kibana-tls
      hosts:
        - kibana.liormilliger.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

# Volume mounts for the elasticsearch certificate
extraVolumes:
  - name: elastic-certs
    secret:
      secretName: elasticsearch-master-certs

extraVolumeMounts:
  - name: elastic-certs
    mountPath: /usr/share/kibana/config/certs/
    readOnly: true
    